### ISSUE TITLE
Update Dimensions & Metrics to recent changes in datapoints

### ISSUE THREAD

**Issue by IronistM** [jdeboer/ganalytics#3]
For example a Query cannot use the experimentId, experimentVariant dimensions

> GaDimensions(gaQuery) <- c("date","experimentId")
Error in validObject(.Object) : 
  invalid class “gaDimVar” object: Invalid GA dimension name: experimentId

**Comment by jdeboer** [comment]
All dimensions and metrics should now be supported thanks to the Google Analytics Meta Data API. There is a function named `ganalytics:::GaMetaUpdate()` that can be run before building the package any time the list of dimensions or metrics needs to be refreshed. Users of the package should not need to do this themselves though, as the system data file that holds this information will be regularly updated in this repository to support the usual installation steps performed using`devtools`.
