### ISSUE TITLE
[README] Set your system environment variables

### ISSUE THREAD

**Issue by unikum** [jdeboer/ganalytics#4]
For set your system environment variables you can use `Sys.setenv(GANALYTICS_CONSUMER_ID = "<Your client ID>", GANALYTICS_CONSUMER_SECRET = "<Your client secret>")`. Also you can use `.Renviron` on unix-like systems.

**Comment by jdeboer** [comment]
Thanks Artem, that is a good idea and I think it makes it easier for users that do not mind having their client secret contained in their R script.

I have been working on another way to supply the OAuth credentials that offers greater flexibility and will hopefully be less work for end users. The [gcalendar](https://github.com/jdeboer/gcalendar) package employs this new technique. The example provided in the readme for the gcalendar package I think explains. I would be interested to hear what you think of it.

Kind regards,

Johann.

**Comment by jdeboer** [comment]
I have included your suggestions in the Readme. Thanks.
