### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by kongjqr** [jdeboer/ganalytics#60]
![image](https://user-images.githubusercontent.com/36258484/35960991-e2d755cc-0ce6-11e8-8774-92f6ad2c27d2.png)

Any idea how we can resolve this problem

**Comment by jdeboer** [comment]
Hi @kongjqr. Thank you for reporting this issue. I've been working on development changes and had mistakenly left in a dependency for some functionality from another package that is not yet available on CRAN. I've removed that dependency so the installation should work now. Please let me know if you continue to face any problems with the installation.
